name: build and test

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_VERSION: '3.1.413' # The .NET SDK version to use
  IN_CI: 'true'

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
#        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Init Submodules
        run: git submodule update --init --recursive
      - name: Install dependencies
        run: dotnet restore     
      - name: Build
        run: dotnet build Chaincase.Tests --configuration Release --no-restore
      - name: Install E2E Tools
        run: dotnet tool install --global Microsoft.Playwright.CLI
      - name: Install Browser binaries
        run: playwright install
      - name: Test
        run: dotnet test Chaincase.Tests --no-restore
